on: [push]

jobs:
  ansible_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: run the the container
      id: playbook
      uses: actions/ansible-container@v1
      with:
        playbook: 'playbook.yml'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.playbook.outputs.time }}"
