on: [push]

jobs:
  ansible_job:
    runs-on: ubuntu-latest
    name: A job to run the ansible container
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: run the the container test
      id: playbook
      uses: 'ctrlShiftBryan/ansible-container-action@main'
      with:
        playbook: 'playbook.yml'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.playbook.outputs.time }}"
